# Generated by Django 6.0.6 on 2026-06-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrolladora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_operativo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=150)),
                ('memoria_ram', models.CharField(max_length=50)),
                ('tarjeta_grafica', models.CharField(max_length=150)),
                ('almacenamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('categorias', models.ManyToManyField(related_name='juegos', to='tienda.categoria')),
                ('desarrolladora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='tienda.desarrolladora')),
                ('plataformas', models.ManyToManyField(related_name='juegos', to='tienda.plataforma')),
                ('requisitos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.requisitossistema')),
            ],
        ),
    ]
