# Generated by Django 6.0.6 on 2026-06-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='requisitos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.requisitossistema'),
        ),
    ]
